# NAS Panel Server Configuration - External MQTT
server:
  hostname: "auto"  # auto to detect hostname automatically, or specify manually
  ip: "auto"  # auto to detect, or specify manually like "192.168.1.100"
  
mqtt:
  type: "external"  # Use external MQTT broker
  host: "localhost"  # External MQTT broker host
  port: 1883  # External MQTT broker port
  topic: "nas/panel/data"
  qos: 1
  # username: "mqtt_user"  # Optional: MQTT username
  # password: "mqtt_password"  # Optional: MQTT password
  client_id: "nas_panel_server"  # Optional: MQTT client ID
  keep_alive: 60  # Optional: Keep alive interval
  
collection:
  interval: 5  # seconds
  
# Custom collection parameters
custom_collectors: []
  # Example: add custom temperature sensors
  # - name: "gpu_temp"
  #   type: "file"
  #   path: "/sys/class/thermal/thermal_zone1/temp"
  #   transform: "lambda x: float(x) / 1000"
  #   unit: "°C"
